#!/bin/bash
if (($# == 0)) || (($# > 2)); then
else
   echo "usage:   ./scp-all node_num [dataset]"

   echo
   echo "parms:"
   echo "node_num      required - node the files will be copied to (using scp)"
   echo "dataset       optional - defaults to parquet_sf3000"
   echo
   echo "              assumes dataset is located in /raid (currently hardcoded)"
   echo
   echo "exmaples:"
   echo 
   echo "   1) copy all files in parquet_sf3000 (all sub-directories) to dgx-hera-29"
   echo
   echo "      ./scp-all 25"
   echo
   echo "   2) copy all files in parquet_10tb_gpu/store_sales to dgx-hera-17"
   echo 
   echo "      ./scp-all 17 parquet_10t_gpu/store_sales"
   exit 1
fi

node=$1


echo "-------------------------------------------------------------------------------------------"
# node number (required)
node=$1
node_name=dgx-hera-$node

#TODO for now it is assumed the datasets are in /raid, could take as parm
dataset_dir="/raid"
dataset="parquet_sf3000"   # defualt if $2 not specified
if (($# == 2)); then
   dataset=$2
fi
echo "dataset: [$dataset_dir]/$dataset"

echo "-------------------------------------------------------------------------------------------"
echo          scp to root@dgx-hera-$node
echo "-------------------------------------------------------------------------------------------"

#TODO using xargs for /xxx/yyy/store_sales is less efficient - should check tor this case

# note it is important to note add tailing / on the from, but inlcude it on the to (scp is fussy)
ls $dataset_dir|$dataset xargs -I{} bash -c "scp -r $dataset_dir/$dataset/{} root@dgx-hera-$node:$dataset_dir/$dataset/ "
